# Generated by Django 3.1.7 on 2021-04-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210309_1509'),
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSideItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order_side_item_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('drink_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.sidesanddrinks')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderSideitems', to='checkout.order')),
            ],
        ),
    ]
