# Generated by Django 3.1.7 on 2021-03-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dietaryrequirements',
            options={'verbose_name_plural': 'Dietary Requirements'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='sidesanddrinks',
            options={'verbose_name_plural': 'Sides and Drinks'},
        ),
    ]
